# This is a config for E2B sandbox template.
# You can use template ID (8h0caaieibktwg8vzp7x) or template name (ollio) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("ollio") # Sync sandbox
# sandbox = await AsyncSandbox.create("ollio") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('ollio')

team_id = "aa6e04a7-f891-467e-a1bd-32a0b32e3bde"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "ollio"
template_id = "8h0caaieibktwg8vzp7x"
